### ISSUE TITLE
nerd fonts look weird with vim and logo-ls 

### ISSUE THREAD

**Issue by siduck76** [gnotclub/xst#124] opened 2020-12-01 03:14 UTC
nerd fonts look cut half in nerdtree in vim and logo-ls icons too 
![image](https://user-images.githubusercontent.com/59060246/100692693-5e583880-33b1-11eb-9855-014bbe6649a5.png) , it works in st tho :/ . 

xst 
![image](https://user-images.githubusercontent.com/59060246/100695703-c873dc00-33b7-11eb-8b18-279585f3c7c4.png)

st

![image](https://user-images.githubusercontent.com/59060246/100695714-d0cc1700-33b7-11eb-9611-9b2372cd130a.png)

**Comment by actionless** [comment] 2020-12-01 13:39
try to analyze the overall difference between your config.h of st VS config.h + xresources of xst

and post it here

**Comment by actionless** [comment] 2020-12-01 13:42
if the problem still persists even while you totally sure configurations are the same -- try to `git-bisect` in xst at which commit it got broken

but my current guess it's a difference in font size or smth like using "Nerd Mono" in one and "Monospace" (resolving to the same Nerd Mono) in other or such kind of config things

**Comment by siduck76** [comment] 2020-12-01 14:44
> if the problem still persists even while you totally sure configurations are the same -- try to `git-bisect` in xst at which commit it got broken
> 
> but my current guess it's a difference in font size or smth like using "Nerd Mono" in one and "Monospace" (resolving to the same Nerd Mono) in other or such kind of config things

that works but now the icon size is getting very small 

(with font : JetBrainsMono Nerd Font Mono )
![image](https://user-images.githubusercontent.com/59060246/100754900-9a22ea80-3411-11eb-985c-1480290b4e10.png)

(with font : JetBrainsMono Nerd Font ) 
![image](https://user-images.githubusercontent.com/59060246/100755078-cb031f80-3411-11eb-88db-a08e3edaa654.png)

**Comment by actionless** [comment] 2020-12-01 15:17
i still not convinced wht the same setting works differently in st vs xst

**Comment by siduck76** [comment] 2020-12-01 15:35
> i still not convinced wht the same setting works differently in st vs xst

st on the left 
![image](https://user-images.githubusercontent.com/59060246/100761417-e4f43080-3418-11eb-9c69-1aa38710c9a9.png)

**Comment by actionless** [comment] 2020-12-01 15:48
ok, let's do it other way around:

1) build totally vanilla st and xst, without any changes to config.h
2) reset your xrdb:

```
$ xrdb -q
$ xrdb -load /dev/null
$ xrdb -q
```

3) force the same font via cli arg:
st -f 'Meslo LG S for Lcarsline:pixelsize=20:antialias=true'

**Comment by siduck76** [comment] 2020-12-01 16:01
> :pixelsize=20:antialias=true'

st 
![image](https://user-images.githubusercontent.com/59060246/100764562-7b762100-341c-11eb-91fc-63d6cad6c062.png)

xst 

![image](https://user-images.githubusercontent.com/59060246/100764603-8466f280-341c-11eb-9a8a-c31e79a676b3.png)

**Comment by actionless** [comment] 2020-12-01 16:05
are you sure what font name and font size are the same?

on your screenshots xst evidentially have bigger font (however i don't think xst does any dpi-multiplication of font size or such, especially when xrdb is reset, it's for sure not obtaining any display information from xcb directly and such

it seems what in this situation the only resort is doing `git bisect`

btw just a sidenote, i can't reproduce it when doing the same steps as in my previous comment

**Comment by siduck76** [comment] 2020-12-01 16:08
> are you sure what font name and font size are the same?
> 
> on your screenshots xst evidentially have bigger font (however i don't think xst does any dpi-multiplication of font size or such, especially when xrdb is reset, it's for sure not obtaining any display information from xcb directly and such
> 
> it seems what in this situation the only resort is doing `git bisect`
> 
> btw just a sidenote, i can't reproduce it when doing the same steps as in my previous comment

st seemed to have smaller font since that was the vanilla ST , with no xresources patch . Idk what git bisect does

**Comment by actionless** [comment] 2020-12-01 16:10
if you runned `xrdb` commands above xresources patch shouldn't make any difference

>  Idk what git bisect does

https://stackoverflow.com/questions/4713088/how-to-use-git-bisect

**Comment by siduck76** [comment] 2020-12-01 16:11
oh that looks complex :l

**Comment by actionless** [comment] 2020-12-01 16:25
i have one more last idea to try before bisect-ing, in `xst` config.h tr to adjust `unsigned int max_bold_weight_infelicity = 20;` to `0`

**Comment by siduck76** [comment] 2020-12-01 16:31
oh that doesnt work either :(

**Comment by actionless** [comment] 2020-12-01 16:38
just to double-check, what' the output of your `xrdb -q` command while you did last test attempts?

**Comment by actionless** [comment] 2020-12-01 16:38
(it must be empty, if you followed the steps without accedents)

**Comment by siduck76** [comment] 2020-12-02 05:17
yeah it was empty but still doesnt fix the issue :(

**Comment by actionless** [comment] 2020-12-02 14:29
at this point the only possible solution i see what you (or anyone else who able to reproduce the issue) will do git bisect

**Comment by siduck76** [comment] 2020-12-03 08:49
> at this point the only possible solution i see what you (or anyone else who able to reproduce the issue) will do git bisect

oh nvm I'll just make my own st build now

**Closed** 2020-12-03 09:40 UTC
Labels: need info
