### ISSUE TITLE
Crashing Terminal

### ISSUE THREAD

**Issue by ganifladi** [gnotclub/xst#61] opened 2018-12-31 17:36 UTC
Hey! First at all i really enjoy using this terminal. Thanks for keeping it alive.

But recently i have encountered some trouble with it. E.g. when i try to search some music in mpsyt or open my mailbox in neomutt, the terminal will crash. The programs run fine until that point. Maybe it has some problems with rendering big lists or something. I already reinstalled the terminal, but this didn't prevent ther terminal from crashing ;(

Here are some information about my system:
OS: Manjaro Linux 4.19.12-2
terminal version (installed from AUR): xst-git 20181014.5d2206e-1
email client (installed from AUR): NeoMutt 20180716
mpsyt 0.2.8

If you need more information, just asked. I don't know what to do about it, except asking here for help.

**Comment by actionless** [comment] 2018-12-31 19:42
run terminal from another terminal and collect xst-s stdout/err at the moment of crashing

**Comment by ganifladi** [comment] 2019-01-02 19:20
Thanks for your quick response!
I did as you suggested (open other terminal and start xst from in there) and this is the output after the crash:

**NeoMutt**
X Error of failed request:  BadLength (poly request too large or internal Xlib length error)
Major opcode of failed request:  139 (RENDER)
Minor opcode of failed request:  20 (RenderAddGlyphs)
Serial number of failed request:  4220
Current serial number in output stream:  4256

**mpsyt**
X Error of failed request:  BadLength (poly request too large or internal Xlib length error)
Major opcode of failed request:  139 (RENDER)
Minor opcode of failed request:  20 (RenderAddGlyphs)
Serial number of failed request:  1931
Current serial number in output stream:  2159

Is there anything else i can help with?

**Comment by ganifladi** [comment] 2019-01-05 19:47
I changed the font from 'hack' to 'noto sans' and the output is only slightly different for _neomutt_:

```
X Error of failed request:  BadLength (poly request too large or internal Xlib length error)
Major opcode of failed request:  139 (RENDER)
Minor opcode of failed request:  20 (RenderAddGlyphs)
Serial number of failed request:  3970
Current serial number in output stream:  4022
```

Maybe my Xresources could be helpful to track it down:

```
! https://github.com/neeasade/xst/blob/master/doc/Xresources

st.termname:            xst-256color
st.shell:               /usr/bin/fish
!st.font:                Hack:pixelsize=16:antialias=true:autohint=true;
st.font:                Noto Sans:pixelsize=16;
st.borderpx:            40
st.cursorshape:         2
st.cursorthickness:     2
st.cursorblinkstyle:    0
st.cursorblinkontype:   1
st.bold_font:           0
st.xfps:                120
st.actionfps:           30
st.opacity:     255

! Kerning / character bounding-box height multiplier
st.chscale:           1.0
! Kerning / character bounding-box width multiplier
st.cwscale:           1.0
! blinking timeout for terminal and cursor blinking (0 disables)
st.blinktimeout:      800
! bell volume. Value between -100 and 100. (0 disables)
st.bellvolume:        0
! this is a char that is exposed like so: `printf '\033[z'`
st.prompt_char:       $
```

**Comment by actionless** [comment] 2019-01-05 20:16
and can you reproduce the same problem in `st`?

**Comment by ganifladi** [comment] 2019-01-06 13:41
Yes, i could reproduce it with _st 0.8.1_ in _neomutt_ and _mpsyt_:

```
X Error of failed request:  BadLength (poly request too large or internal Xlib length error)
Major opcode of failed request:  139 (RENDER)
Minor opcode of failed request:  20 (RenderAddGlyphs)
Serial number of failed request:  3994
Current serial number in output stream:  4038
```

I disabled my fish shell, but had no luck as well. Everything works fine in konsole. Anything else i could try?

**Comment by actionless** [comment] 2019-01-06 14:06
i'd suggest raising a question in st mailing list, since they have muuch bigger community than xst

**Comment by neeasade** [comment] 2020-12-03 17:41
fyi: https://lists.suckless.org/dev/1901/33147.html

**Comment by actionless** [comment] 2020-12-03 18:25
i think it's ok to close it here

**Closed by actionless** 2020-12-03 18:25 UTC
Labels: upstream issue
