### ISSUE TITLE
Upgrade to 0.8.x?

### ISSUE THREAD

**Issue by carlitos777** [gnotclub/xst#82] opened 2020-01-01 22:04 UTC
Heyyo,
Thanks for this awesome st build.
Any chance to bump version to latest st?

Thanks,
carlitos

**Comment by ralsei** [comment] 2020-03-30 13:36
Is anyone *not* okay with me attempting this (in a branch, obviously)? I have commit access to this repository, technically, albeit I haven't worked on it as of yet.

**Comment by actionless** [comment] 2020-03-30 18:20
@ralsei, would be super nice, just please don't push it directly to master, but give some time for people around to test the PR

**Comment by ralsei** [comment] 2020-03-30 18:38
oh of course, yeah, that's what the new branch `rebase-0.8.2` is for

**Comment by ygworldr** [comment] 2020-05-04 19:03
st `0.8.3` is out.

**Comment by tmpm697** [comment] 2020-05-28 09:03
if it's okay, anyone can push to aur?

**Comment by neeasade** [comment] 2020-07-03 04:35
hi all, 

At the start of `xst` a friend and I had plans to do more poking at it than ever happened, which is why we changed the layout (bikeshed) and with some other things over time, merging is a little icky. I'm going to revert to upstream st's repo and then apply patches + xst changes. I've gathered some notes (org format) for order and how I'm going to sync on the `2020_reset` branch. /cc @actionless 

```
**** list of patches/things to account for in xst

[bankruptcy]

goals:
- match upstream repo layout
- keep `xst` in terminfo and binary name
- make merging in the future easy

approach:
- start with current upstream
- apply wanted patches
- makefile + terminfo --> s/st/xst/
- implement current xst-specific (no upstream) patches

***** TODO spoiler
***** TODO clipboard
***** TODO externalpipe
***** TODO boldcolors (only the ability to disable bold fonts)
***** TODO vertcenter
***** TODO alpha (transparent background)
***** TODO cursor blinking
thinking we can outsource to this patch https://st.suckless.org/patches/blinking_cursor/
will need to make up the width options on underline and pipe shape

***** TODO delpatch
check if this is now handled in terminfo/by $TERM

***** ---- from here down  is xst-specific stuff -----

***** TODO hidecursor patch? https://github.com/gnotclub/xst/pull/65
thinking no, just recommend unclutter to whoever wants this

***** TODO borderless window patch https://github.com/gnotclub/xst/commit/dda53ae9edaecb09a929388917ea7cdfcaa38fa6

***** TODO max_bold_weight_infelicity
https://github.com/gnotclub/xst/commit/7679315a6746c4a9c59409ebdeb7d95e9f1c2488
https://github.com/gnotclub/xst/commit/8519227bcef14712d9eff1c8919a31ef1b629eb7

***** TODO IMStyle
https://github.com/gnotclub/xst/pull/37/files
https://github.com/gnotclub/xst/commit/bcc622d591c06e4e1df1b2b36a1c1a66c4a8421e

***** TODO Premultiply R,G and B when using transparency.
https://github.com/gnotclub/xst/commit/360ef337ea66c1d38f3b1a715fc1b8a5312513f8

***** TODO xresources loading
```

**Comment by actionless** [comment] 2020-07-03 12:23
i went through the list it looks fine, but i'm not sure about blinking patch, i think having `cursorblinkontype` option is important

**Comment by neeasade** [comment] 2020-07-03 13:56
@actionless sounds good, I hadn't given the upstream patch a close look yet

**Comment by neeasade** [comment] 2020-07-03 20:12
alright, blinking patch is the last thing, I think we're ready beyond that, will take a look later(tm)

**Comment by arkhan** [comment] 2020-07-04 00:08
Greetings, what great news.

You could consider the next patch https://st.suckless.org/patches/ligatures/

Thanks

**Comment by neeasade** [comment] 2020-07-04 01:59
@arkhan sure, after i'll take a look after this is pushed out/consider -- adding a link to that patch over on #71. 

@actionless would you mind testing the 2020_reset branch? should be all sync'd up now, just sanity check on someone else's config might be nice

**Comment by neeasade** [comment] 2020-07-04 23:08
merged it

**Closed by neeasade** 2020-07-04 23:08 UTC

**Comment by actionless** [comment] 2020-07-04 23:41
> Not supported patches
>    alpha: use a compositor such as picom to make xst windows transparent

when using external compositor, text also becomes transparent

**Comment by neeasade** [comment] 2020-07-05 00:18
> when using external compositor, text also becomes transparent

good point. I re-applied the patch on branch `alpha` but I currently have a bug where I have no window border on alpha windows.

**Comment by actionless** [comment] 2020-07-05 00:30
border -- you mean the one defined by `st.borderpx`?

**Comment by neeasade** [comment] 2020-07-05 00:37
no -- I mean window manager border -- combination is `bspwm` + `compton` v7.5

**Comment by actionless** [comment] 2020-07-05 00:45
was you able to reproduce the same problem in xst 0.7?

**Comment by neeasade** [comment] 2020-07-05 00:59
I was not -- here's a screenshot https://0x0.st/iyQN.png -- from top to bottom (right to left): 

- xst v8.4.0 alpha 255
- xst v0.8.4 alpha 150
- xst v7 alpha 150 
- xst v7 alpha 255

(where alpha 255 is max value)

**Comment by actionless** [comment] 2020-07-05 01:46
and patch is only in one commit? i can try to look into it during the sunday afternoon

**Comment by arkhan** [comment] 2020-07-05 02:45
I just tried this and it's great, what I don't see is working is the cursorshape since I put it on the value of 4 but in the terminal it continues showing as if it was parameterized with 2

**Comment by neeasade** [comment] 2020-07-05 03:02
> and patch is only in one commit? i can try to look into it during the sunday afternoon

it is -- https://github.com/gnotclub/xst/commit/be52e877458351c8166bf33b01487cf8412d2bcb much appreciated if you can. do note there's a small change from [og patch](https://st.suckless.org/patches/alpha/st-alpha-0.8.2.diff) I made for [this commit](https://github.com/gnotclub/xst/commit/360ef337ea66c1d38f3b1a715fc1b8a5312513f8)

**Comment by neeasade** [comment] 2020-07-05 15:23
@arkhan thanks for the bug report -- fixed with https://github.com/gnotclub/xst/pull/90

**Comment by actionless** [comment] 2020-07-06 16:34
@neeasade i've reviewed your patch and tested on practice:

1) i can't reproduce the border issue, try with few other WMs -- it seems what your WM gets confused by (missing of?) some of X attrs, namely try some major well-known-not-to-be-buggy WM like openbox;
2) although i found a problem in pre-multiply patch adoptation and filed a PR with the fix: https://github.com/gnotclub/xst/pull/94
2.1) going back to a very previous discussion, i still think that pre-multiplication is a bit questionable move, so i suggest making it optional (however don't mind it to be enabled by default).

**Comment by neeasade** [comment] 2020-07-06 17:20
@actionless sounds good -- I'll take your word re: 1. I'll make it optional/on by default in that PR. thanks for taking a look!

**Comment by tmpm697** [comment] 2020-07-12 09:26
I have same issue with border, but only with newest update `1:0.8.4.r8.ga4dd66d-1`

look total different from previous version. in my case the color look brighter than previous ones.
